server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  
  datasource:
    name: userMicroservice
    url: jdbc:mysql://localhost:3306/userMicroservice
    username: root
    password: English@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
    show-sql: true
    
    hibernate:
      ddl-auto: update
      
  config:
    import: configserver:http://localhost:8085
         
#eureka:
#  instance:
#    prefer-ip-address: true
#    
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
 